//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorevYoneticisi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICI()
        {
            this.GOREV = new HashSet<GOREV>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Bu Alan Gereklidir")]
        public string Kullanici_Adi { get; set; }
        [Required(ErrorMessage = "Bu Alan Gereklidir")]
        public string Sifre { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOREV> GOREV { get; set; }
    }
}
